### PR TITLE
make Roles in SecurityRolesType translateable

### LINKED ISSUE #911: Symfony Roles with hierachy are not translateable in SecurityRolesType
#### Sonata packages

```
sonata-project/admin-bundle              3.23.0             = 3.23.0
sonata-project/block-bundle              3.4.0              = 3.4.0
sonata-project/cache                     1.0.7              = 1.0.7
sonata-project/core-bundle               3.5.1              = 3.5.1
sonata-project/datagrid-bundle           2.2.1              = 2.2.1
sonata-project/doctrine-extensions       1.0.2              = 1.0.2
sonata-project/doctrine-orm-admin-bundle 3.1.7              = 3.1.7
sonata-project/easy-extends-bundle       2.2.0              = 2.2.0
sonata-project/exporter                  1.7.1              = 1.7.1
sonata-project/user-bundle               dev-master a962eaa = dev-master a962eaa
```

#### Symfony packages

```
symfony/assetic-bundle     v2.8.2 = v2.8.2
symfony/monolog-bundle     v3.1.0 = v3.1.0
symfony/phpunit-bridge     v3.3.9 = v3.3.9
symfony/polyfill-apcu      v1.5.0 = v1.5.0
symfony/polyfill-intl-icu  v1.5.0 = v1.5.0
symfony/polyfill-mbstring  v1.5.0 = v1.5.0
symfony/polyfill-php56     v1.5.0 = v1.5.0
symfony/polyfill-php70     v1.5.0 = v1.5.0
symfony/polyfill-util      v1.5.0 = v1.5.0
symfony/security-acl       v3.0.0 = v3.0.0
symfony/swiftmailer-bundle v2.6.3 ~ v3.0.4
symfony/symfony            v3.3.9 = v3.3.9
```

#### PHP version

```
PHP 7.1.2 (cli) (built: Feb 14 2017 21:38:43) ( ZTS MSVC14 (Visual C++ 2015) x86 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.3, Copyright (c) 2002-2017, by Derick Rethans
```

## Subject

Symfony Roles are not translateable when using Roles for User Admin secruity when they have hierachy.

## Steps to reproduce
use `sonata.admin.security.handler.role` as `sonata_admin.security.handler`
have `security.role_hierarchy` with a role with hierachy like `ROLE_ADMIN:             [ROLE_USER, ROLE_SONATA_ADMIN]`
show the Secruity on a User in Backend.
## Expected results
`Translation not found. {"id":"ROLE_ADMIN","domain":"messages","locale":"de"}`
## Actual results
`Translation not found. {"id":"ROLE_ADMIN: ROLE_USER, ROLE_SONATA_ADMIN","domain":"messages","locale":"de"}`

## The Problem

Is how SecurityRolesType and EditableRolesBuilder does handle the Roles for the Form input is done,
That EditableRolesBuilder does already concat the Role and the subroles together, then SecurityRolesType just pass that list to it's parent ChoiceType.

## Possible Solution
The Role names should be translated before being concat, then SecurityRolesType should use false translation domain to show that the names are already translated

## PS
also the parent rules should problably not be added when SecurityRolesType expanded isn't set to true

## EDIT

- now that PR sonata-project/SonataAdminBundle#4670 got merged, the translation of the Roles can be disabled with `'choice_translation_domain' => false`

### PR DESCRIPTION
**Pull request by Hanmac**
I am targeting this branch, because it most likely not backwards compatible.
I did some big changes with the Role Builder which might not be able to be backwards compatible.
it might not be problematic if it count as internal class.

Also it depends on sonata-project/SonataAdminBundle#4670

Closes #911

## Changelog

```markdown
### Added
- make Roles in SecurityRolesType translateable
```

## To do

- [X] Update the tests

## Subject

SecurityRolesType gets option for `choice_translation_domain` to translate the roles.
It is used similar then in ChoiceType.
Its fallback uses `translation_domain` or the `SonataAdmin#getTranslationDomain`
if used inside SonataAdmin. if false is used, it disable the translation.

some changes for how the choice values are made, to prevent translation of the roles if they are not needed.

The RolesBuilder now has extra funtions for getRoles and getRolesReadOnly to prevent the list from generated twice for the choices and read_only_choices.
it uses TranslatorInterface to translate the roles given to the choice_translation_domain
the Expanded parameter is used to check if the choice will be rendered as Checkboxes (expanded) or as Select (not expanded) because the rolesHierarchy doesn't look so good for Select choices.

Because the RolesBuilder already does translate the roles, i disabled `choice_translation_domain` for the view to prevent double translation. (this needs sonata-project/SonataAdminBundle#4670)

### CODE REVIEW

**Comment by greg0ire** [comment]
> it depends  sonata-project/SonataAdminBundle#4670

But this has been merged in 3.x, right?

**Comment by Hanmac** [comment]
@greg0ire i will update your requests until weekend if able
does your "Please remove this" mean the comment above it or the iterateAdminRoles function itself?

also the StyleCI says something about classes i did touch like `Entity/GroupManager.php` should they be upated too, or should i just ignore them?
also it does move the __ methods to a different place, i think it did it because of the name, if i remove the __ part, it should probably doesn't want to move them right?


about the AdminBundle one, oh i did'nt noticed in which branch it got merged,
hm in cases of Backwards Compatible, i might try to get this one backwards too.

for the Travis problems, it says "The option "sonata_admin" does not exist." but i am sure i have seen it while building it. i will write around it so in case it might or might not exist.

**Comment by greg0ire** [comment]
>  does your "Please remove this" mean the comment above it or the iterateAdminRoles function itself?

the comment above

> also the StyleCI says something about classes i did touch like Entity/GroupManager.php should they be upated too, or should i just ignore them?

You should update them, not your fault of course, but we literally cannot merge unless you or someone else does it and you rebase

>  hm in cases of Backwards Compatible, i might try to get this one backwards too.

That would be great!

**Comment by greg0ire** [comment]
> Fixed StyleCI 2 

Please kindly squash your commits together. If you don't, we'll try to remember to do it for you but it's best if you save us this trouble.

How to do that?

1. `git rebase -i origin/3.x`, assuming `origin` is a git remote that points to this repository, and not your fork. If you're not sure what your remotes are, run `git remote -vvv`, there should be your fork and the holy/reference/base/origin/whatever-you-call-it repository.
2. A window will show up with many lines, replace `pick` with `fixup` on every line but the first one
3. Close your editor, git should do its magic, and you should end up with one commit
4. Use `git push --force` to overwrite what you already pushed. Don't forget the `--force` option otherwise git will try to merge both things together.

**Comment by Hanmac** [comment]
@greg0ire the commits will be squashed when the tests are clean
and yeah i can try the rebase later after that

**Comment by Hanmac** [comment]
@greg0ire i don't know if you are the right one to help me, but i currently don't understand why that one testcase does fail while the from Hierachy testcase does work

currently have no way to test on my system to run this in steps

**Comment by Hanmac** [comment]
@greg0ire i did rebase it and fixup the commits against master to make it more clean (one commit)
i don't know if i can easy rebase that against 3.0 because of different Folder structure?

i tried, but i failed a few times, probably confused `--theirs` and `--ours`

File: Security/EditableRolesBuilder.php [hunk 1]
```diff
@@ -51,18 +57,80 @@ public function __construct(TokenStorageInterface $tokenStorage, AuthorizationCh
         $this->rolesHierarchy = $rolesHierarchy;
     }
 
+    public function setTranslator(TranslatorInterface $translator)
```
Comment (OskarStark) [inline Security/EditableRolesBuilder.php]: phpdoc missing

**Comment by Hanmac** [comment]
@OskarStark i added it and rebase it (so only one commit)

now i need to try to rebase it somehow against 3.0

**Comment by Hanmac** [comment]
@greg0ire managed to rebased against `3.0`
waiting for the travis tests to pass

**Comment by Hanmac** [comment]
@greg0ire @OskarStark the tests are somehow halted after i did the rebase
do i need to start it again somehow?

**Comment by OskarStark** [comment]
This one is failing:
```
There was 1 failure:
1) Sonata\UserBundle\Tests\Form\Type\SecurityRolesTypeTest::testSubmitWithHiddenRoleData
Failed asserting that false is true.
```

File: tests/Form/Transformer/RestoreRolesTransformerTest.php [hunk 2]
```diff
@@ -62,7 +62,7 @@ public function testValidReverseTransform()
             ->disableOriginalConstructor()
             ->getMock();
```
Comment (OskarStark) [inline tests/Form/Transformer/RestoreRolesTransformerTest.php]: can you please replace:
```diff
- $roleBuilder = $this->getMockBuilder('Sonata\UserBundle\Security\EditableRolesBuilder')->disableOriginalConstructor()->getMock();
+ $roleBuilder = $this->createMock(EditableRolesBuilder::class);
```

same for the other

**Comment by Hanmac** [comment]
@OskarStark yeah seen this
Try to fix it at work
My quess it's about the flipped choices for the Form Type that need to be removed for 2.8

For the Replacement yes, I just did keep that way it was, I thought it had a reason

**Comment by OskarStark** [comment]
> For the Replacement yes, I just did keep that way it was, I thought it had a reason

its fine, but would be great if you could fix it this way, as you are working in the class right now, but an extra commit would be nice

File: src/Form/Type/SecurityRolesType.php [hunk 3]
```diff
@@ -111,7 +111,10 @@ public function configureOptions(OptionsResolver $resolver)
                 }
                 $roles = $rolesBuilder->getRoles($options['choice_translation_domain'], $options['expanded']);
 
-                return array_flip($roles);
+                /*
+                 * NEXT_MAJOR: array_flip §roles
```
Comment (OskarStark) [inline src/Form/Type/SecurityRolesType.php]: $, not §

**Comment by Hanmac** [comment]
@OskarStark sorry i dismissed your review, i did stash the commits again to make them nicer

the tests does pass, but showed some warning for `COMPOSER_FLAGS="--prefer-lowest"`
https://travis-ci.org/sonata-project/SonataUserBundle/jobs/302416724

i think they got something to do with older phpunit versions and should not be my problem

File: composer.json [hunk 4]
```diff
@@ -28,7 +28,8 @@
         "symfony/console": "^2.8",
         "symfony/form": "^2.8",
         "symfony/http-foundation": "^2.8",
-        "symfony/security": "^2.8"
+        "symfony/security": "^2.8",
+        "symfony/translation": "^2.8"
```
Comment (greg0ire) [inline composer.json]: What if the user does not wish to use i18n?

**Comment by Hanmac** [comment]
@greg0ire you mean like in a sense of disable the translation for the Form type, or don't install it at all?

Don't installing might not work because sonata admin already require translation in composer,

But I think I can move the setTranslator call into the Extension to check first if the translation service is on

**Comment by greg0ire** [comment]
The question I'm asking here is: "why wasn't that dependency already here?"

1. is it because it is optional?
2. if not, is it because someone forgot to add it?
3. or is it because the user bundle did not need to translate anything anywhere?

**Comment by Hanmac** [comment]
@greg0ire 

from dependency wise:
user bundle needs admin bundle, and this already depends on symfony/translation,
so it might not be needed that user bundle does depend of translation if admin bundle already depends on it

code wise
did check on the other code of the user bundle and it used tranlator service once in the AdminResettingController
and use of trans actions in the twig file

for my part, i can make it that EditableRolesBuilder works without translation
(it's already in the class, i would just moved the setTranslator call into the SonataUserExtension for dynamic check)

**Comment by greg0ire** [comment]
Don't bother, if the translation is mandatory, it's better to not kid yourselves and try to make it optional for no one.

**Comment by Hanmac** [comment]
@greg0ire also if the user doesn't want to translate the roles, he can use `"choice_translation_domain" => false` this does disable the translation of them where the form type is used

**Comment by greg0ire** [comment]
There is one unchecked item in your todo list, are you done with it?

**Comment by Hanmac** [comment]
thanks, i forgot to update that after the tests did pass

**Comment by greg0ire** [comment]
Thanks @Hanmac !

**Comment by Hanmac** [comment]
Great that this got merged!

for master, do i need to do some changes again or are you guys doing it?
i think the only thing that need to be done is that array_flip back again

**Comment by greg0ire** [comment]
@Hanmac it's best if you do the changes yourself. Please monitor master to see when your 3.x gets merged into master.

**Comment by Hanmac** [comment]
@greg0ire i didn't mean it for myself i mean if i need to make a new PR or something like that to update the this code for your master branch again
(see the array_flip thing that need to be done in master)

or if you guys will already take care of that

**Comment by greg0ire** [comment]
It's best if you make a new PR or something like that to update the this code for your master branch again. lease monitor master to see when your 3.x gets merged into it.

**Comment by Hanmac** [comment]
so i would do it again, fork from master into new branch, apply the changes fix them for symfony 3.0+
and make a new PR?

but wouldn't that be a problem if you guys try to merge 3.0 into master again?
or isn't that my problem? XD

**Comment by greg0ire** [comment]
1. wait for your changes to land on master
2. do whatever major changes can be done in a new PR
3. any merge subsequent merge problems are ours to handle, but there probably won't be many.
