### PR TITLE
Roles matrix group by admin and admin group

### LINKED ISSUE #1583: Incorrect display acl privileges grid, when exists two admin entity with the same name (in other groups).
#### Sonata packages

<details><summary>show</summary>
<p>

```
sonata-project/admin-bundle              4.18.0 ! 4.21.0 The missing Symfony Admin Generator
sonata-project/block-bundle              4.16.2 ! 4.19.0 Symfony SonataBlockBundle
sonata-project/cache                     2.2.0  = 2.2.0  Cache library
sonata-project/cache-bundle              3.4.0  = 3.4.0  This bundle provides caching services
sonata-project/doctrine-extensions       1.18.0 ~ 2.0.1  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 4.6.0  ! 4.8.0  Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  3.0.0  = 3.0.0  Lightweight Exporter library
sonata-project/form-extensions           1.18.0 = 1.18.0 Symfony form extensions
sonata-project/intl-bundle               2.14.0 ~ 3.0.2  Symfony SonataIntlBundle
sonata-project/media-bundle              4.2.0  ! 4.5.1  Symfony SonataMediaBundle
sonata-project/translation-bundle        3.1.0  = 3.1.0  SonataTranslationBundle
sonata-project/twig-extensions           1.12.0 ~ 2.0.0  Sonata twig extensions
sonata-project/user-bundle               5.4.0  = 5.4.0  Symfony SonataUserBundle
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
symfony/acl-bundle                 v2.3.0  = v2.3.0  Symfony AclBundle
symfony/amqp-messenger             v5.4.11 ~ v6.1.7  Symfony AMQP extension Messenger Bridge
symfony/apache-pack                v1.0.1  = v1.0.1  A pack for Apache support in Symfony
symfony/asset                      v5.4.7  ~ v6.1.5  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/browser-kit                v5.4.11 ~ v6.1.3  Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/cache                      v5.4.11 ~ v6.1.7  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.5.2  ~ v3.1.1  Generic abstractions related to caching
symfony/config                     v5.4.11 ~ v6.1.3  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v5.4.11 ~ v6.1.7  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v5.4.11 ~ v6.1.3  Converts CSS selectors to XPath expressions
symfony/debug-bundle               v5.4.11 ~ v6.1.3  Provides a tight integration of the Symfony VarDumper component and the ServerLogCommand from MonologBridge into the Symfony full-stack framework
symfony/dependency-injection       v5.4.11 ~ v6.1.5  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v3.1.1  = v3.1.1  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v5.4.11 ~ v6.1.7  Provides integration for Doctrine with various Symfony components
symfony/doctrine-messenger         v5.4.11 ~ v6.1.4  Symfony Doctrine Messenger Bridge
symfony/dom-crawler                v5.4.11 ~ v6.1.7  Eases DOM navigation for HTML and XML documents
symfony/dotenv                     v5.4.5  ~ v6.1.0  Registers environment variables from a .env file
symfony/error-handler              v5.4.11 ~ v6.1.7  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.4.9  ~ v6.1.0  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v3.1.1  = v3.1.1  Generic abstractions related to dispatching event
symfony/expression-language        v5.4.11 ~ v6.1.6  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v5.4.11 ~ v6.1.5  Provides basic utilities for the filesystem
symfony/finder                     v5.4.11 ~ v6.1.3  Finds files and directories via an intuitive fluent interface
symfony/flex                       v2.2.3  = v2.2.3  Composer plugin for Symfony
symfony/form                       v5.4.11 ~ v6.1.7  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v5.4.11 ~ v6.1.7  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                v5.4.11 ~ v6.1.7  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v2.5.2  ~ v3.1.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.4.11 ~ v6.1.7  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.4.11 ~ v6.1.7  Provides a structured process for converting a Request into a Response
symfony/intl                       v5.4.11 ~ v6.1.7  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mailer                     v5.4.11 ~ v6.1.7  Helps sending emails
symfony/maker-bundle               v1.45.0 ! v1.48.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger                  v5.4.11 ~ v6.1.6  Helps applications send and receive messages to/from other applications or via message queues
symfony/mime                       v5.4.11 ~ v6.1.7  Allows manipulating MIME messages
symfony/monolog-bridge             v5.4.10 ~ v6.1.2  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.8.0  = v3.8.0  Symfony MonologBundle
symfony/notifier                   v5.4.8  ~ v6.1.0  Sends notifications via one or more channels (email, SMS, ...)
symfony/options-resolver           v5.4.11 ~ v6.1.0  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v5.4.11 ~ v6.1.3  Provides password hashing utilities
symfony/phpunit-bridge             v6.1.3  ! v6.1.6  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-intl-grapheme     v1.26.0 ! v1.27.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.26.0 ! v1.27.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.26.0 ! v1.27.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.26.0 ! v1.27.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.26.0 ! v1.27.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56             v1.20.0 = v1.20.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php73             v1.26.0 ! v1.27.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.26.0 ! v1.27.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81             v1.26.0 ! v1.27.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/process                    v5.4.11 ~ v6.1.3  Executes commands in sub-processes
symfony/property-access            v5.4.11 ~ v6.1.7  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v5.4.11 ~ v6.1.7  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v5.4.6  ~ v6.1.0  Provides integration for ProxyManager with various Symfony components
symfony/redis-messenger            v5.4.6  ~ v6.1.7  Symfony Redis extension Messenger Bridge
symfony/routing                    v5.4.11 ~ v6.1.7  Maps an HTTP request to a set of configuration variables
symfony/runtime                    v5.4.11 ~ v6.1.3  Enables decoupling PHP applications from global state
symfony/security-acl               v3.3.1  ! v3.3.2  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v5.4.11 ~ v6.1.3  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core              v5.4.11 ~ v6.1.7  Symfony Security Component - Core Library
symfony/security-csrf              v5.4.11 ~ v6.1.0  Symfony Security Component - CSRF Library
symfony/security-guard             v5.4.9  ! v5.4.13 Symfony Security Component - Guard
symfony/security-http              v5.4.11 ~ v6.1.7  Symfony Security Component - HTTP Integration
symfony/serializer                 v5.4.11 ~ v6.1.6  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/service-contracts          v2.5.2  ~ v3.1.1  Generic abstractions related to writing services
symfony/stopwatch                  v5.4.5  ~ v6.1.5  Provides a way to profile code
symfony/string                     v5.4.11 ~ v6.1.7  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/swiftmailer-bundle         v3.5.4  = v3.5.4  Symfony SwiftmailerBundle
symfony/templating                 v5.4.11 ~ v6.1.3  Provides all the tools needed to build any kind of template system
symfony/translation                v5.4.11 ~ v6.1.6  Provides tools to internationalize your application
symfony/translation-contracts      v2.5.2  ~ v3.1.1  Generic abstractions related to translation
symfony/twig-bridge                v5.4.11 ~ v6.1.7  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v5.4.8  ~ v6.1.1  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v5.4.11 ~ v6.1.7  Provides tools to validate values
symfony/var-dumper                 v5.4.11 ~ v6.1.6  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.4.10 ~ v6.1.3  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                   v5.4.3  ~ v6.1.0  Manages links between resources
symfony/web-profiler-bundle        v5.4.10 ~ v6.1.6  Provides a development tool that gives detailed information about the execution of any request
symfony/webpack-encore-bundle      v1.15.1 ! v1.16.0 Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v5.4.11 ~ v6.1.6  Loads and dumps YAML files

```

</p>
</details>

#### PHP version

```
PHP 8.1.12 (cli) (built: Oct 28 2022 17:39:37) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.12, Copyright (c), by Zend Technologies

```

## Subject
Incorrect display acl privileges grid, when exists two admin entity with the same name (in other groups).

## Steps to reproduce
Create two admin entity with the same name.
For example:

```
    admin.menu:
      class: App\Admin\MenuAdmin
      arguments: [~, App\Entity\Menu, 'App\Controller\Admin\SortableController', '@doctrine.orm.default_entity_manager']
      tags:
        - { name: sonata.admin, manager_type: orm, group: 'Menu', label: 'List' }
    
    admin.news:
      class: App\Admin\NewsAdmin
      arguments: [~, App\Entity\News, ~, '@doctrine.orm.default_entity_manager']
      tags:
        - { name: sonata.admin, manager_type: orm, group: 'Article', label: 'List'}
```

## Expected results
image

## Actual results
image

I think an attribute that allows to change the name displayed in the ACL editor would be a good solution.

### PR DESCRIPTION
**Pull request by piddubnij**
## Subject

Admin roles attribute "admin_label" set admin translation domain
Roles matrix group by admin and admin group
Admin roles sort by admin config and group config

I am targeting this branch, because this is BC.

Closes #1583.

## Changelog

```markdown
### Changed
- RolesBuilder: add attributes "admin_code", "group_label", "group_code".
### Fixed
- Fix RolesBuilder attribute "admin_label" set admin translation domain
- Fix roles matrix attribute "admin_label" can repeat not even in different groups but also in the same group
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Hi @piddubnij, sorry for the delay ; do you have a screenshot of the result ?

File: src/Twig/RolesMatrixExtension.php [hunk 1]
```diff
@@ -71,14 +71,15 @@ public function renderMatrix(Environment $environment, FormView $form): string
     {
         $groupedRoles = [];
         foreach ($this->rolesBuilder->getRoles() as $role => $attributes) {
-            if (!isset($attributes['admin_label'])) {
+            if (!isset($attributes['admin_code'])) {
```
Comment (VincentLanglet) [inline src/Twig/RolesMatrixExtension.php:74]: This is a BC-break for people using this extensions with their own data.

If we change that much the job of this method
- either we create a new one
- either we keep BC with deprecation for the old behavior.

File: src/Twig/RolesMatrixExtension.php [hunk 2]
```diff
@@ -71,14 +71,15 @@ public function renderMatrix(Environment $environment, FormView $form): string
...
                 continue;
             }
 
-            $groupedRoles[$attributes['admin_label']][$role] = $attributes;
+            $groupCode = $attributes['group_code'] ?? '_';
```
Comment (VincentLanglet) [inline src/Twig/RolesMatrixExtension.php]: The `_` default seems weird.

File: src/Security/RolesBuilder/AdminRolesBuilder.php [hunk 3]
```diff
@@ -76,27 +78,65 @@ public function addExcludeAdmin(string $exclude): void
...
+
+        return $adminRoles;
+    }
+
+    /**
+     * @return array<string, array<string, string|bool>>
+     *
+     * @phpstan-return array<string, Role>
+     */
+    private function getAdminRolesByAdminCode(string $code, ?string $domain = null, string $groupLabelTranslated = '_', string $groupCode = '_'): array
```
Comment (VincentLanglet) [inline src/Security/RolesBuilder/AdminRolesBuilder.php]: The `_` default seems weird.

File: src/Security/RolesBuilder/AdminRolesBuilder.php [hunk 4]
```diff
@@ -76,27 +78,65 @@ public function addExcludeAdmin(string $exclude): void
...
-                    'admin_label' => $admin->getTranslator()->trans($admin->getLabel() ?? ''),
-                ];
+                $groupLabelTranslated = $this->translator->trans($group['label'], [], $group['translation_domain']);
+
+                $adminRoles = array_merge($adminRoles, $this->getAdminRolesByAdminCode($item['admin'], $domain, $groupLabelTranslated, $groupCode));
             }
         }
 
+        // admin with config "show_in_dashboard" set "false" does not have group
+        $defaultGroupLabelTranslated = $this->translator->trans('_', [], $domain);
```
Comment (VincentLanglet) [inline src/Security/RolesBuilder/AdminRolesBuilder.php]: i'm not sure to understand the trans of `_` ; won't this be reported as a missing translations for lot of people ?

**Review by VincentLanglet — CHANGES_REQUESTED** [review]
I thought the proposal in https://github.com/sonata-project/SonataUserBundle/issues/1583#issuecomment-1321769128 was "just" to change

```
List
List
Media
...
```
to
```
Article - List
Menu - List
sonata_media - Media
...
```

Wasn't the implementation proposed possible ?
Because the one proposed in the issue seemed BC when this one is introducing BC-break

**Comment by piddubnij** [comment]
> Hi @piddubnij, sorry for the delay ; do you have a screenshot of the result ?

result-1

File: src/Twig/RolesMatrixExtension.php (hunk 1 above)
Comment (piddubnij) [reply src/Twig/RolesMatrixExtension.php:74]: Attribute "admin_label" can repeat not even in different groups but also in the same group. I don't know how to avoid this change. If group not set or "show_in_dashboard" set to "false" admin does not have group.

File: src/Twig/RolesMatrixExtension.php (hunk 2 above)
Comment (piddubnij) [reply src/Twig/RolesMatrixExtension.php]: How to group admins without group? I can replace it to "default".

File: src/Security/RolesBuilder/AdminRolesBuilder.php (hunk 3 above)
Comment (piddubnij) [reply src/Security/RolesBuilder/AdminRolesBuilder.php]: "groupLabelTranslated" empty string is better? groupCode replace to "default" ?

File: src/Security/RolesBuilder/AdminRolesBuilder.php (hunk 4 above)
Comment (piddubnij) [reply src/Security/RolesBuilder/AdminRolesBuilder.php]: Replace to empty string or "Default"?

File: src/Twig/RolesMatrixExtension.php (hunk 1 above)
Comment (VincentLanglet) [reply src/Twig/RolesMatrixExtension.php:74]: Yeah I understand. That's maybe why the previous suggestion was to use `Group - Name` in the same value, rather than having a group key and a label key.

What you may do is 
```
if (!isset($attributes['admin_code'])) {
    // NEXT_MAJOR: Remove this code.
    if (isset($attributes['admin_label']) {
        // trigger a deprecation

        // apply the old behavior
    }

     continue;
```
WDYT, would it be possible to do something like this ?

File: src/Security/RolesBuilder/AdminRolesBuilder.php (hunk 4 above)
Comment (VincentLanglet) [reply src/Security/RolesBuilder/AdminRolesBuilder.php]: Might be better to use empty string indeed. And this won't require a translator call :)

File: src/Security/RolesBuilder/AdminRolesBuilder.php (hunk 3 above)
Comment (VincentLanglet) [reply src/Security/RolesBuilder/AdminRolesBuilder.php]: Yeah, I think empty string will be better.

File: src/Twig/RolesMatrixExtension.php (hunk 2 above)
Comment (VincentLanglet) [reply src/Twig/RolesMatrixExtension.php]: Let's go with empty string. If we would have use `null` it would have been casted to `''` when used as an array key so, that's a good representation I would think.

File: src/Twig/RolesMatrixExtension.php (hunk 1 above)
Comment (piddubnij) [reply src/Twig/RolesMatrixExtension.php:74]: > Yeah I understand. That's maybe why the previous suggestion was to use `Group - Name` in the same value, rather than having a group key and a label key.

To avoid repeat labels need something like:
```
$groupLabels=[];
$adminLabels=[];

$i=0; $k=0;
foreach ($admins as $admin){
    if(!isset($groupLabels[$admin['group_code']))
    {
        $groupLabel=$admin['group_label'];
        if(array_search($admin['group_label'], $groupLabels, true)!==false)
        {
            $groupLabel=$admin['group_label'].'('.++$i.')';
        }

        $groupLabels[$admin['group_code']]=$groupLabel;
    }

    if(!isset($adminLabels[$admin['group_code']][$admin['admin_code']))
    {
        $adminLabel=$admin['admin_label'];
        if(array_search($admin['admin_label'], $adminLabels[$admin['group_code']], true)!==false)
        {
            $adminLabel=$admin['admin_label'].'('.++$k.')';
        }

        $adminLabels[$admin['group_code']][$admin['admin_code']]=$adminLabel;
    }
}
```
Result 
Group_1 - Name_1,
Group_1(1) - Name_2,
Group_2 - Name_1,
Group_2(2) - Name_1(1),

> WDYT, would it be possible to do something like this ?
```
if (!isset($attributes['admin_code'])) {
    // NEXT_MAJOR: Uncomment
    // continue;

    // NEXT_MAJOR: Remove this code.
    // trigger a deprecation
    if (!isset($attributes['admin_label'])) {
        continue;
    }

    $attributes['admin_code'] = $attributes['admin_label'];
}
```
How to properly trigger a deprecation?

It is better implement deprecation or Group - Name ?

Comment (VincentLanglet) [reply src/Twig/RolesMatrixExtension.php:74]: > How to properly trigger a deprecation?

We're using
```
        @trigger_error(sprintf(
            'Foo is deprecated since sonata-project/foo-lib 42.x and will be removed in version 43.0.',
        ), \E_USER_DEPRECATED);
```

> It is better implement deprecation or Group - Name ?

I'm fine with both. I just wanted to avoid the BC-break.

Comment (piddubnij) [reply src/Twig/RolesMatrixExtension.php:74]: Done. Not sure if deprecation message is correct.

File: src/Security/RolesBuilder/AdminRolesBuilder.php [hunk 5]
```diff
@@ -76,27 +78,63 @@ public function addExcludeAdmin(string $exclude): void
...
-                $adminRoles[$role] = [
-                    'role' => $role,
-                    'label' => $key,
-                    'role_translated' => $this->translateRole($role, $domain),
-                    'is_granted' => $this->isMaster($admin) || $this->authorizationChecker->isGranted($role),
-                    'admin_label' => $admin->getTranslator()->trans($admin->getLabel() ?? ''),
-                ];
+                $groupLabelTranslated = $this->translator->trans($group['label'], [], $group['translation_domain']);
+
+                $adminRoles = array_merge($adminRoles, $this->getAdminRolesByAdminCode($item['admin'], $domain, $groupLabelTranslated, $groupCode));
```
Comment (piddubnij) [inline src/Security/RolesBuilder/AdminRolesBuilder.php:99]: First test fail in line 99.
TypeError: Argument 3 passed to must be of the type string, null given.

File: src/Security/RolesBuilder/AdminRolesBuilder.php [hunk 6]
```diff
@@ -76,27 +78,63 @@ public function addExcludeAdmin(string $exclude): void
...
-            foreach (array_keys($admin->getSecurityInformation()) as $key) {
-                $role = sprintf($baseRole, $key);
-                $adminRoles[$role] = [
-                    'role' => $role,
-                    'label' => $key,
-                    'role_translated' => $this->translateRole($role, $domain),
-                    'is_granted' => $this->isMaster($admin) || $this->authorizationChecker->isGranted($role),
-                    'admin_label' => $admin->getTranslator()->trans($admin->getLabel() ?? ''),
-                ];
+                $groupLabelTranslated = $this->translator->trans($group['label'], [], $group['translation_domain']);
```
Comment (piddubnij) [inline src/Security/RolesBuilder/AdminRolesBuilder.php:97]: Do I need to check is trans() method return string despite interface Symfony\Contracts\Translation\TranslatorInterface promise string?

Comment (VincentLanglet) [reply src/Security/RolesBuilder/AdminRolesBuilder.php:97]: You mean because of the failing tests ? I didn't take a look at the failure, but maybe you just need to mock the trans call in the tests.

Comment (piddubnij) [reply src/Security/RolesBuilder/AdminRolesBuilder.php:97]: Yes.
Unfortunately, I still do not understand the tests well and have no idea how to do it.
If you have the possibility to help me with this, that would be great.

**Review by VincentLanglet — APPROVED** [review]

**Comment by piddubnij** [comment]
@VincentLanglet Thank you 👍🏻
