### PR TITLE
Fix compatibility with doctrine/persistence 2.0

### LINKED ISSUE #1331: Compatibility with doctrine/common 3.0
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.89.1 3.89.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.22.0 4.5.0  Symfony SonataBlockBundle
sonata-project/cache                     2.1.1  2.1.1  Cache library
sonata-project/datagrid-bundle           3.3.0  3.3.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.11.0 1.11.0 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.29.0 3.29.0 Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.5.1  2.5.1  Lightweight Exporter library
sonata-project/form-extensions           1.9.0  1.9.0  Symfony form extensions
sonata-project/media-bundle              3.30.0 3.30.0 Symfony SonataMediaBundle
sonata-project/twig-extensions           1.5.1  1.5.1  Sonata twig extensions
sonata-project/user-bundle               4.11.0 4.11.0 Symfony SonataUserBundle
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/amqp-messenger             v5.2.3  v5.2.3  Symfony AMQP extension Messenger Bridge
symfony/asset                      v4.4.19 v5.2.3  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/cache                      v5.2.3  v5.2.3  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.2.0  v2.2.0  Generic abstractions related to caching
symfony/config                     v4.4.19 v5.2.3  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v4.4.19 v5.2.3  Eases the creation of beautiful and testable command line interfaces
symfony/debug                      v4.4.19 v4.4.19 Provides tools to ease debugging PHP code
symfony/debug-bundle               v4.4.19 v5.2.3  Provides a tight integration of the Symfony Debug component into the Symfony full-stack framework
symfony/dependency-injection       v4.4.19 v5.2.3  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v2.2.0  v2.2.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v4.4.19 v5.2.3  Provides integration for Doctrine with various Symfony components
symfony/doctrine-messenger         v5.2.3  v5.2.3  Symfony Doctrine Messenger Bridge
symfony/dotenv                     v5.2.3  v5.2.3  Registers environment variables from a .env file
symfony/error-handler              v4.4.19 v5.2.3  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v4.4.19 v5.2.3  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v1.1.9  v2.2.0  Generic abstractions related to dispatching event
symfony/expression-language        v5.2.3  v5.2.3  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v5.2.3  v5.2.3  Provides basic utilities for the filesystem
symfony/finder                     v5.2.3  v5.2.3  Finds files and directories via an intuitive fluent interface
symfony/flex                       v1.12.2 v1.12.2 Composer plugin for Symfony
symfony/form                       v4.4.19 v5.2.3  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v4.4.19 v5.2.3  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client-contracts      v2.3.1  v2.3.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v4.4.19 v5.2.3  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v4.4.19 v5.2.3  Provides a structured process for converting a Request into a Response
symfony/intl                       v5.2.3  v5.2.3  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mailer                     v5.2.3  v5.2.3  Helps sending emails
symfony/maker-bundle               v1.29.1 v1.29.1 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger                  v5.2.3  v5.2.3  Helps applications send and receive messages to/from other applications or via message queues
symfony/mime                       v5.2.3  v5.2.3  Allows manipulating MIME messages
symfony/monolog-bridge             v5.2.3  v5.2.3  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.6.0  v3.6.0  Symfony MonologBundle
symfony/options-resolver           v5.2.3  v5.2.3  Provides an improved replacement for the array_replace PHP function
symfony/phpunit-bridge             v5.2.3  v5.2.3  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-intl-grapheme     v1.22.1 v1.22.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.22.1 v1.22.1 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.22.1 v1.22.1 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.22.1 v1.22.1 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.22.1 v1.22.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php80             v1.22.1 v1.22.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                    v5.2.3  v5.2.3  Executes commands in sub-processes
symfony/property-access            v5.2.3  v5.2.3  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v5.2.3  v5.2.3  Extracts information about PHP class' properties using metadata of popular sources
symfony/redis-messenger            v5.2.3  v5.2.3  Symfony Redis extension Messenger Bridge
symfony/routing                    v4.4.19 v5.2.3  Maps an HTTP request to a set of configuration variables
symfony/security-acl               v3.1.1  v3.1.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.4.19 v5.2.3  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core              v4.4.19 v5.2.3  Symfony Security Component - Core Library
symfony/security-csrf              v5.2.3  v5.2.3  Symfony Security Component - CSRF Library
symfony/security-guard             v4.4.19 v5.2.3  Symfony Security Component - Guard
symfony/security-http              v4.4.19 v5.2.3  Symfony Security Component - HTTP Integration
symfony/service-contracts          v2.2.0  v2.2.0  Generic abstractions related to writing services
symfony/stopwatch                  v5.2.3  v5.2.3  Provides a way to profile code
symfony/string                     v5.2.3  v5.2.3  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/templating                 v4.4.19 v5.2.3  Provides all the tools needed to build any kind of template system
symfony/translation                v4.4.19 v5.2.3  Provides tools to internationalize your application
symfony/translation-contracts      v2.3.0  v2.3.0  Generic abstractions related to translation
symfony/twig-bridge                v4.4.19 v5.2.3  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v4.4.19 v5.2.3  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v4.4.19 v5.2.3  Provides tools to validate values
symfony/var-dumper                 v5.2.3  v5.2.3  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.2.3  v5.2.3  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-profiler-bundle        v4.4.19 v5.2.3  Provides a development tool that gives detailed information about the execution of any request
symfony/webpack-encore-bundle      v1.11.1 v1.11.1 Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v5.2.3  v5.2.3  Loads and dumps YAML files
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 7.4.15 (cli) (built: Feb  9 2021 19:48:41) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies
    with Xdebug v3.0.2, Copyright (c) 2002-2021, by Derick Rethans
```

## Subject

When upgrading to the latest release of this bundle, I've got an error with the registration of FosUserBundle commands.
The cause is this PR: https://github.com/sonata-project/SonataUserBundle/pull/1325

That PR upgraded the doctrine/common and persistence packages to the next major version, giving some protection layer with FOSUser (that it is not compatible).

I have tried the cache:clear or removing completely the cache directory, but it does not work.

## Steps to reproduce

1. Upgrade SontaUserBundle and doctrine/* packages related.
2. Try to execute some console commands

## Expected results

Execute commands without warnings or errors.

## Actual results

```
 [WARNING] Some commands could not be registered:

In UserManager.php line 41:

  Argument 3 passed to FOS\UserBundle\Doctrine\UserManager::__construct() mus
  t be an instance of Doctrine\Common\Persistence\ObjectManager, instance of
  Doctrine\ORM\EntityManager given, called in /usr/app/var/cache/dev/Containe
  rD8hTDUh/getSonata_User_UserManagerService.php on line 16
```

### LINKED ISSUE #1336: Argument 3 passed to FOS\UserBundle\Doctrine\UserManager in sonata-project/user-bundle
**Hi,
After installing sonata-project/user-bundle I get this issue.**
Argument 3 passed to FOS\UserBundle\Doctrine\UserManager::__construct() must be an instance of Doctrine\Common\Persiste     nce\ObjectManager, instance of ContainerATvBIog\EntityManager_9a5be93 given.
This is my composer :
```json
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": ">=7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "composer/package-versions-deprecated": "1.11.99.1",
        "doctrine/annotations": "^1.0",
        "doctrine/common": "3.1.*",
        "doctrine/doctrine-bundle": "^2.2",
        "doctrine/doctrine-migrations-bundle": "^3.0",
        "doctrine/orm": "^2.8",
        "phpdocumentor/reflection-docblock": "^5.2",
        "sensio/framework-extra-bundle": "^5.1",
        "sonata-project/admin-bundle": "3.88.0",
        "sonata-project/doctrine-orm-admin-bundle": "^3.30",
        "sonata-project/google-authenticator": "^2.3",
        "sonata-project/user-bundle": "^4.11",
        "symfony/asset": "4.4.*",
        "symfony/console": "4.4.*",
        "symfony/dotenv": "4.4.*",
        "symfony/expression-language": "4.4.*",
        "symfony/flex": "^1.3.1",
        "symfony/form": "4.4.*",
        "symfony/framework-bundle": "4.4.*",
        "symfony/http-client": "4.4.*",
        "symfony/intl": "4.4.*",
        "symfony/mailer": "4.4.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/process": "4.4.*",
        "symfony/property-access": "4.4.*",
        "symfony/property-info": "4.4.*",
        "symfony/proxy-manager-bridge": "4.4.*",
        "symfony/security-bundle": "4.4.*",
        "symfony/serializer": "4.4.*",
        "symfony/translation": "4.4.*",
        "symfony/twig-bundle": "^4.4",
        "symfony/validator": "4.4.*",
        "symfony/web-link": "4.4.*",
        "symfony/yaml": "4.4.*",
        "twig/extra-bundle": "^2.12|^3.0",
        "twig/twig": "2.13.*"
    },
    "require-dev": {
        "symfony/browser-kit": "^4.4",
        "symfony/css-selector": "^4.4",
        "symfony/debug-bundle": "^4.4",
        "symfony/maker-bundle": "^1.0",
        "symfony/phpunit-bridge": "^5.2",
        "symfony/stopwatch": "^4.4",
        "symfony/var-dumper": "^4.4",
        "symfony/web-profiler-bundle": "^4.4"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "4.4.*"
        }
    }
}
```

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

Class aliases need to be created on a place that it is always executed,
previous code was only executed on an empty cache. Next request were
always broken. Moving to the bundle class ensures the code is always
executed.

I am targeting this branch, because this is a bugfix and BC.

Closes #1331
Closes #1336

## Changelog

```markdown
### Fixed
- Fix compatibility with doctrine/persistence 2.0
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
Well, it works on a project, but not on the test suite, any ideas?

**Comment by phansys** [comment]
IMO, these aliases are not really required by this package, but by "friendsofsymfony/user-bundle". Maybe we should just move them to `tests/bootstrap.php` in order to allow our test suite to pass the build.
The final users should declare these aliases in their own bootstrapping, since the issue around them is not actually under our responsibility.

**Comment by VincentLanglet** [comment]
> IMO, these aliases are not really required by this package, but by "friendsofsymfony/user-bundle". Maybe we should just move them to `tests/bootstrap.php` in order to allow our test suite to pass the build.
> The final users should declare these aliases in their own bootstrapping, since the issue around them is not actually under our responsibility.

It should be in `custom_boostrap` then.
https://github.com/sonata-project/SonataUserBundle/blob/4.x/tests/bootstrap.php#L27

**Comment by jordisala1991** [comment]
> IMO, these aliases are not really required by this package, but by "friendsofsymfony/user-bundle". Maybe we should just move them to `tests/bootstrap.php` in order to allow our test suite to pass the build.
> The final users should declare these aliases in their own bootstrapping, since the issue around them is not actually under our responsibility.

Well, you are declaring this package as compatible with doctrine/persistence 2.0, but this package has a dependency that is not compatible. IMHO we either fix this with code like this one, or we can't do this. Someone just updates this packages and then code stops working.

Agree on adding it to tests/bootstrap.php if that fixes the issue, but as I explained before I don't think that is the responsability of each user to know what we did here and add some alias so have the bundle working again.

**Comment by VincentLanglet** [comment]
We could declare the BC method as a static one and call it every where we need the BC layer

**Comment by phansys** [comment]
I think using `SonataUserBundle::boot()` for projects and `tests/custom_bootstrap.php` for the test suite is the best approach.

**Comment by phansys** [comment]
@jordisala1991, do you have time to finish this PR?

**Comment by jordisala1991** [comment]
I will try tomorrow, yes

**Review by phansys — APPROVED** [review]

File: src/SonataUserBundle.php [hunk 1]
```diff
@@ -58,4 +59,19 @@ public function registerFormMapping(): void
             ]);
         }
     }
+
+    /**
+     * We MUST remove this method when support for "friendsofsymfony/user-bundle" is dropped
+     * or adapted to work with "doctrine/common:^3".
+     */
+    private function createDoctrineCommonBackwardCompatibilityAliases(): void
```
Comment (VincentLanglet) [inline src/SonataUserBundle.php:67]: What about making this method public static in order to call it in the custom_boostrap ?

**Review by VincentLanglet — APPROVED** [review]

File: src/SonataUserBundle.php (hunk 1 above)
Comment (jordisala1991) [reply src/SonataUserBundle.php:67]: Then it would be bc break to remove it, IMO not a good idea.

**Comment by phansys** [comment]
Thank you @jordisala1991.
