### PR TITLE
Exclude ROLE_DEFAULT from RoleMatrixType

### LINKED ISSUE #1535: ROLE_USER in RoleMatrixType visible without effect
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              4.11.1 4.11.1 The missing Symfony Admin Generator
sonata-project/block-bundle              4.12.0 4.12.0 Symfony SonataBlockBundle
sonata-project/cache                     2.2.0  2.2.0  Cache library
sonata-project/doctrine-extensions       1.16.0 1.16.0 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 4.2.8  4.2.8  Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.11.0 2.11.0 Lightweight Exporter library
sonata-project/form-extensions           1.13.1 1.13.1 Symfony form extensions
sonata-project/twig-extensions           1.9.1  1.9.1  Sonata twig extensions
sonata-project/user-bundle               5.1.0  5.1.0  Symfony SonataUserBundle
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/asset                      v5.4.7  v5.4.7  Manages URL generation and versioning of web assets such as CSS s...
symfony/cache                      v5.4.8  v5.4.8  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.5.1  v2.5.1  Generic abstractions related to caching
symfony/config                     v5.4.8  v5.4.8  Helps you find, load, combine, autofill and validate configuratio...
symfony/console                    v5.4.8  v5.4.8  Eases the creation of beautiful and testable command line interfaces
symfony/dependency-injection       v5.4.8  v5.4.8  Allows you to standardize and centralize the way objects are cons...
symfony/deprecation-contracts      v2.5.1  v2.5.1  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v5.4.8  v5.4.8  Provides integration for Doctrine with various Symfony components
symfony/dotenv                     v5.4.5  v5.4.5  Registers environment variables from a .env file
symfony/error-handler              v5.4.8  v5.4.8  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.4.3  v5.4.3  Provides tools that allow your application components to communic...
symfony/event-dispatcher-contracts v2.5.1  v2.5.1  Generic abstractions related to dispatching event
symfony/expression-language        v5.4.8  v5.4.8  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v5.4.7  v5.4.7  Provides basic utilities for the filesystem
symfony/finder                     v5.4.8  v5.4.8  Finds files and directories via an intuitive fluent interface
symfony/flex                       v1.18.7 v1.18.7 Composer plugin for Symfony
symfony/form                       v5.4.8  v5.4.8  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v5.4.8  v5.4.8  Provides a tight integration between Symfony components and the S...
symfony/http-foundation            v5.4.8  v5.4.8  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.4.8  v5.4.8  Provides a structured process for converting a Request into a Res...
symfony/intl                       v5.4.8  v5.4.8  Provides a PHP replacement layer for the C intl extension that in...
symfony/mailer                     v5.4.8  v5.4.8  Helps sending emails
symfony/maker-bundle               v1.41.0 v1.41.0 Symfony Maker helps you create empty commands, controllers, form ...
symfony/mime                       v5.4.8  v5.4.8  Allows manipulating MIME messages
symfony/monolog-bridge             v5.4.3  v5.4.3  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.7.1  v3.7.1  Symfony MonologBundle
symfony/options-resolver           v5.4.3  v5.4.3  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v5.4.8  v5.4.8  Provides password hashing utilities
symfony/polyfill-intl-grapheme     v1.25.0 v1.25.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.25.0 v1.25.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.25.0 v1.25.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.25.0 v1.25.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.25.0 v1.25.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73             v1.25.0 v1.25.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP ...
symfony/polyfill-php80             v1.25.0 v1.25.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP ...
symfony/polyfill-php81             v1.25.0 v1.25.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP ...
symfony/property-access            v5.4.8  v5.4.8  Provides functions to read and write from/to an object or array u...
symfony/property-info              v5.4.7  v5.4.7  Extracts information about PHP class' properties using metadata o...
symfony/routing                    v5.4.8  v5.4.8  Maps an HTTP request to a set of configuration variables
symfony/runtime                    v5.4.8  v5.4.8  Enables decoupling PHP applications from global state
symfony/security-acl               v3.3.1  v3.3.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v5.4.8  v5.4.8  Provides a tight integration of the Security component into the S...
symfony/security-core              v5.4.8  v5.4.8  Symfony Security Component - Core Library
symfony/security-csrf              v5.4.3  v5.4.3  Symfony Security Component - CSRF Library
symfony/security-guard             v5.4.3  v5.4.3  Symfony Security Component - Guard
symfony/security-http              v5.4.8  v5.4.8  Symfony Security Component - HTTP Integration
symfony/serializer                 v5.4.8  v5.4.8  Handles serializing and deserializing data structures, including ...
symfony/service-contracts          v2.5.1  v2.5.1  Generic abstractions related to writing services
symfony/stopwatch                  v5.4.5  v5.4.5  Provides a way to profile code
symfony/string                     v5.4.8  v5.4.8  Provides an object-oriented API to strings and deals with bytes, ...
symfony/translation                v5.4.8  v5.4.8  Provides tools to internationalize your application
symfony/translation-contracts      v2.5.1  v2.5.1  Generic abstractions related to translation
symfony/twig-bridge                v5.4.8  v5.4.8  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v5.4.8  v5.4.8  Provides a tight integration of Twig into the Symfony full-stack ...
symfony/validator                  v5.4.8  v5.4.8  Provides tools to validate values
symfony/var-dumper                 v5.4.8  v5.4.8  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.4.8  v5.4.8  Allows exporting any serializable PHP data structure to plain PHP...
symfony/web-profiler-bundle        v5.4.8  v5.4.8  Provides a development tool that gives detailed information about...
symfony/yaml                       v5.4.3  v5.4.3  Loads and dumps YAML files
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 7.4.21 (cli) (built: Jul  1 2021 19:26:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.21, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
```

## Minimal repository with the bug
Have SonataUserBundle installed in SonataAdminBundle

## Steps to reproduce
* Edit a User that doesn't has Super Role and try to add the `ROLE_USER` from the RoleMatrixType

## Expected results
* Either the `ROLE_USER` shouldn't be visible, or it should be able to save.
## Actual results
* You can't save the Role to the User.

The Reason is that the Sonata User always has the `ROLE_USER` set internally, shouldn't the RoleMatrixType either:
* always have it Enabled? maybe even that you can't disable it?
* Or not show the Role at all, because you can't enable it?

### PR DESCRIPTION
**Pull request by Hanmac**
## Subject

I am targeting this branch, because it should be BC.

Per default only `UserInterface::ROLE_DEFAULT` aka `ROLE_USER` is excluded, but users can still use it.

If this Component would be moved outside of UserBundle that might be changed.

Closes #1535.

## Changelog

```markdown
### Added
- Added `RoleMatrixType:exclude` Option to hide choices.

```

### CODE REVIEW

**Comment by Hanmac** [comment]
@jordisala1991 is this good for a fix or should i extend the test cases more for the excluded option?

or if for example i set the excluded option to only `[Role_A]` should `UserInterface::ROLE_DEFAULT` still be excluded or not?

**Review by jordisala1991 — DISMISSED** [review]

File: src/Form/Type/RolesMatrixType.php [hunk 1]
```diff
@@ -73,6 +75,7 @@ static function (Options $options, $value) {
 
                     return $value;
                 },
+            'exclude' => [UserInterface::ROLE_DEFAULT],
```
Comment (VincentLanglet) [inline src/Form/Type/RolesMatrixType.php]:
```suggestion
            'excluded_roles' => [UserInterface::ROLE_DEFAULT],
```
to be more specific ?

**Review by VincentLanglet — CHANGES_REQUESTED** [review]

File: src/Form/Type/RolesMatrixType.php (hunk 1 above)
Comment (jordisala1991) [reply src/Form/Type/RolesMatrixType.php]: Also please add docs about this feature

Comment (Hanmac) [reply src/Form/Type/RolesMatrixType.php]: what is your opinions about always excluding `UserInterface::ROLE_DEFAULT` in addition to `excluded_roles` ?

Comment (jordisala1991) [reply src/Form/Type/RolesMatrixType.php]: I would prefer it to be configurable, so no auto addition, wdyt @VincentLanglet ?

Comment (VincentLanglet) [reply src/Form/Type/RolesMatrixType.php]: I agree, seems better to let it always configurable

**Comment by Hanmac** [comment]
* added docs to the rst ones
* used better `excluded_roles` option name
* added more test cases

is that clear or should i add more config option? like defining it an Configuration option?

**Comment by jordisala1991** [comment]
For each option you add to an option resolver is a good practice to provide its allowed types, in this case it should be 'string[]'. Can you add that option?

**Review by VincentLanglet — DISMISSED** [review]

**Comment by Hanmac** [comment]
Your Opinion if that option should be configuable over the Config yml too?

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
> Your Opinion if that option should be configuable over the Config yml too?

I don't think this is needed so far. Less config option is better if not needed.

**Comment by VincentLanglet** [comment]
Is it ok for you @jordisala1991 ?

**Review by jordisala1991 — APPROVED** [review]
