### PR TITLE
TwigExtension configuration setting fix

### LINKED ISSUE #924: Fatal error: You have requested a non-existent parameter "twig.form.resources"
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.23.0             3.23.0             The missing Symfony Admin Generator
sonata-project/block-bundle              3.4.0              3.4.0              Symfony SonataBlockBundle
sonata-project/cache                     1.1.0              2.0.0              Cache library
sonata-project/core-bundle               3.5.1              3.5.1              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1              2.2.1              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.7              3.1.7              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0              2.2.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1              1.7.1              Lightweight Exporter library
sonata-project/formatter-bundle          3.2.3              3.2.3              Symfony SonataFormatterBundle
sonata-project/media-bundle              3.6.0              3.6.0              Symfony SonataMediaBundle
sonata-project/notification-bundle       3.2.0              3.2.0              Symfony SonataNotificationBundle
sonata-project/user-bundle               dev-master c322961 dev-master c322961 Symfony SonataUserBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/assetic-bundle     v2.8.2  v2.8.2  Integrates Assetic into Symfony2
symfony/monolog-bundle     v3.1.1  v3.1.1  Symfony MonologBundle
symfony/phpunit-bridge     v3.3.10 v3.3.10 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.5.0  v1.5.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.5.0  v1.5.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.5.0  v1.5.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.5.0  v1.5.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.5.0  v1.5.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.5.0  v1.5.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.3  v3.1.1  Symfony SwiftmailerBundle
symfony/symfony            v3.2.13 v3.3.10 The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 7.1.10-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep 29 2017 17:04:25) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.10-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```

## Subject

I have installed `SonataUserBundle`. I'm trying to run `php bin/console`, and this is causing next error:
```
$ php bin/console 
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "twig.form.resources". in /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:100
Stack trace:
#0 /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(56): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('twig.form.resou...')
#1 /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(124): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('twig.form.resou...')
#2 /home/vyshkant/www/ancientrus/vendor/sonata-project/user-bundle/DependencyInjection/SonataUserExtension.php(83): Symfony\Component\DependencyInjection\Container->getParameter('twig.form.resou...')
#3 /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfon in /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 100
```
The reason is next.

The `Sonata\UserBundle\DependencyInjection\SonataUserExtension` is trying to add custom form widgets:

https://github.com/sonata-project/SonataUserBundle/blob/c3229613121efbf8f0f8f09e2ec79d8476c4a165/DependencyInjection/SonataUserExtension.php#L81-L85

This function expects the parameter `twig.form.resources` is already set (and the `getParameter` call will not cause an error).

But this parameter might not be set. The `twig.form.resources` parameter is setting by the `TwigBundle` (it gets `twig.form_themes` **config parameter** and then setting `twig.form.resources` **container parameter**). So the `twig.form.resources` is not set before `TwigBundle` is not loaded.

When I modified my `AppKernel::registerBundles` and defined `TwigBundle` before the `SonataUserBundle`, I got rid of the error, shown above.

## Steps to reproduce
1) Install Symfony 3.2.*.
2) Install SonataUserBundle 4.x-dev and put line `new Sonata\UserBundle\SonataUserBundle()` in `AppKernel::registerBundles` **below** the line `new Symfony\Bundle\TwigBundle\TwigBundle()`.
3) Run `php bin/console`.

## Expected results
Default console output.

## Actual results
PHP Fatal error:
```
$ php bin/console 
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "twig.form.resources". in /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:100
Stack trace:
#0 /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/EnvPlaceholderParameterBag.php(56): Symfony\Component\DependencyInjection\ParameterBag\ParameterBag->get('twig.form.resou...')
#1 /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(124): Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag->get('twig.form.resou...')
#2 /home/vyshkant/www/ancientrus/vendor/sonata-project/user-bundle/DependencyInjection/SonataUserExtension.php(83): Symfony\Component\DependencyInjection\Container->getParameter('twig.form.resou...')
#3 /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfon in /home/vyshkant/www/ancientrus/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line 100
```

## Ways to fix ##
I'm not sure what is the best way to fix this issue: we either have to check if the parameter `twig.form.resources` is set (`$container->hasParameter('twig.form.resources')`), or force the user to define the `SonataUserBundle` **after** the `TwigBundle` in `AppKernel::registerBundles` (or both).

In the first case we will not have a guarantee that the custom form widgets will be added.

The second case looks more reliable, but I'm not sure if this is correct from the point of view of the project ideology.

Any ideas? I'll gladly write PR.

### PR DESCRIPTION
**Pull request by vyshkant**
I am targeting this branch, because this fix does not break BC.

Closes #924

## Changelog

```markdown
### Fixed
- Fixed the twig configuration setting bug.
```

## To do

- [x] Update the tests

## Subject

Fixed a bug where the `SonataUserBundle` was causing an exception if the `TwigBundle` was not loaded.

### CODE REVIEW

File: DependencyInjection/SonataUserExtension.php [hunk 1]
```diff
@@ -15,18 +15,29 @@
...
+    public function prepend(ContainerBuilder $container)
+    {
+        if ($container->hasExtension('twig')) {
+            $container->prependExtensionConfig('twig', ['form_themes' => ['SonataUserBundle:Form:form_admin_fields.html.twig']]);
+        }
+    }
+
+    /**
+     * {@inheritdoc}
+     */
```
Comment (greg0ire) [inline DependencyInjection/SonataUserExtension.php]: Is there no need to remove https://github.com/sonata-project/SonataUserBundle/blob/c3229613121efbf8f0f8f09e2ec79d8476c4a165/DependencyInjection/SonataUserExtension.php#L81-L85?

Comment (vyshkant) [reply DependencyInjection/SonataUserExtension.php]: Yes, sure, it has to be removed. It is done now.

**Comment by greg0ire** [comment]
Bonus points if you add tests using https://github.com/matthiasnoback/SymfonyDependencyInjectionTest

**Comment by vyshkant** [comment]
Any idea why the tests failed?

> There was 1 failure:
> 1) Sonata\UserBundle\Tests\Controller\Api\GroupControllerTest::testDeleteGroupInvalidAction
> Failed asserting that exception message is empty but is 'Group (1) not found'.

**Comment by greg0ire** [comment]
Yes.

Please run this to migrate to phpunit5:

```sh
#!/bin/sh
find tests -name PHPUnit_Framework_TestCase.php -delete

grep --recursive --files-with-matches PHPUnit_Framework_TestCase tests|
while read -r test
do
	insertLine=$(($(grep --line-number namespace "$test"|cut --delimiter ':' -f1) + 2))
	sed --in-place "${insertLine}i use PHPUnit\\\\Framework\\\\TestCase;" "$test"
	sed --in-place 's/extends \\PHPUnit_Framework_TestCase/extends TestCase/' "$test"
	sed --in-place 's/extends PHPUnit_Framework_TestCase/extends TestCase/' "$test"
done

grep --recursive --files-with-matches getMock tests|
while read -r test
do
	sed --in-place 's/getMock/createMock/' "$test"
done

rm .php_cs
php-cs-fixer fix . --rules=ordered_imports,single_line_after_imports,no_unused_imports
git checkout .php_cs

```

**Comment by greg0ire** [comment]
See https://github.com/sebastianbergmann/phpunit/issues/2809 for more information

**Comment by vyshkant** [comment]
@greg0ire Launching the script you proposed is causing 26 tests failures.

I think I would be better idea to create a separate PR for tests migration, what do you think?

**Comment by greg0ire** [comment]
Sorry I gave you an outdated, buggy version

**Comment by vyshkant** [comment]
> In a separate PR preferrably.

Should I create PR on the `master` branch or on the `3.x`?

**Comment by greg0ire** [comment]
updated

**Comment by greg0ire** [comment]
Please use 3.x, and then it will get merged into master automatically.

**Comment by vyshkant** [comment]
Do I correctly understand that in order to merge this PR, we must first merge https://github.com/sonata-project/SonataUserBundle/pull/926?

**Comment by greg0ire** [comment]
You do understand correctly :) . When #926 is merge, closing and reopening will trigger a new, hopefully green build.

**Comment by vyshkant** [comment]
> You do understand correctly :) . When #926 is merge, closing and reopening will trigger a new, hopefully green build.

I will now do the tests for this PR using https://github.com/matthiasnoback/SymfonyDependencyInjectionTest

**Comment by vyshkant** [comment]
The problem is that the `prepend` method invocation is implemented, but still **not released** in https://github.com/matthiasnoback/SymfonyDependencyInjectionTest.

And the `prepend` method is actually what I did.

I've created an external issue https://github.com/matthiasnoback/SymfonyDependencyInjectionTest/issues/81 to get next release.

So what can we do now? I can make some workaround of calling the `prepend` method maually. Is it good idea? Or we should wait until the prepend method call functionality will be released on `matthiasnoback/SymfonyDependencyInjectionTest`?

**Comment by vyshkant** [comment]
I decided to update tests after new `SymfonyDependencyInjectionTest` release.

**Comment by greg0ire** [comment]
Thanks @vyshkant!

**Comment by vyshkant** [comment]
> Please use 3.x, and then it will get merged into master automatically.

I expected these changes to be automatically merged into the "master" branch :)

**Comment by greg0ire** [comment]
It happens at night, if there is no conflict ;)

**Comment by greg0ire** [comment]
Well there are conflicts :/
