### PR TITLE
Register UserListener for ORM and ODM

### LINKED ISSUE #1578: SonataUserBundle does not register UserListener with doctrine_mongodb.odm.event_subscriber
### Environment

Ubuntu 22.04 Jammy Jellyfish

#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
Direct dependencies required in composer.json:
sonata-project/admin-bundle                  4.20.0 4.20.0 The missing Symfony Admin Generator
sonata-project/doctrine-mongodb-admin-bundle 4.6.0  4.6.0  Symfony Sonata / Integrate Doctrine MongoDB ODM into the SonataAdminBundle
sonata-project/user-bundle                   5.4.0  5.4.0  Symfony SonataUserBundle

Transitive dependencies not required in composer.json:
sonata-project/block-bundle                  4.18.0 4.19.0 Symfony SonataBlockBundle
sonata-project/cache                         2.2.0  2.2.0  Cache library
Package sonata-project/cache is abandoned, you should avoid using it. No replacement was suggested.
sonata-project/doctrine-extensions           2.0.1  2.0.1  Doctrine2 behavioral extensions
sonata-project/exporter                      3.0.0  3.0.0  Lightweight Exporter library
sonata-project/form-extensions               1.18.0 1.18.0 Symfony form extensions
sonata-project/twig-extensions               2.0.0  2.0.0  Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
Direct dependencies required in composer.json:
symfony/asset                      v6.1.5  v6.1.5  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/browser-kit                v6.1.3  v6.1.3  Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/console                    v6.1.6  v6.1.6  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v6.1.3  v6.1.3  Converts CSS selectors to XPath expressions
symfony/debug-bundle               v6.1.3  v6.1.3  Provides a tight integration of the Symfony VarDumper component and the ServerLogCommand from MonologBridge into the Symfony full-stack framework
symfony/doctrine-messenger         v6.1.4  v6.1.4  Symfony Doctrine Messenger Bridge
symfony/dotenv                     v6.1.0  v6.1.0  Registers environment variables from a .env file
symfony/expression-language        v6.1.6  v6.1.6  Provides an engine that can compile and evaluate expressions
symfony/flex                       v2.2.3  v2.2.3  Composer plugin for Symfony
symfony/form                       v6.1.5  v6.1.5  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v6.1.6  v6.1.6  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                v6.1.6  v6.1.6  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/intl                       v6.1.6  v6.1.6  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mailer                     v6.1.5  v6.1.5  Helps sending emails
symfony/maker-bundle               v1.47.0 v1.47.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mime                       v6.1.6  v6.1.6  Allows manipulating MIME messages
symfony/monolog-bundle             v3.8.0  v3.8.0  Symfony MonologBundle
symfony/notifier                   v6.1.0  v6.1.0  Sends notifications via one or more channels (email, SMS, ...)
symfony/phpunit-bridge             v6.1.6  v6.1.6  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/process                    v6.1.3  v6.1.3  Executes commands in sub-processes
symfony/property-access            v6.1.3  v6.1.3  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v6.1.6  v6.1.6  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v6.1.0  v6.1.0  Provides integration for ProxyManager with various Symfony components
symfony/runtime                    v6.1.3  v6.1.3  Enables decoupling PHP applications from global state
symfony/security-bundle            v6.1.3  v6.1.3  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/serializer                 v6.1.6  v6.1.6  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/stopwatch                  v6.1.5  v6.1.5  Provides a way to profile code
symfony/string                     v6.1.6  v6.1.6  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                v6.1.6  v6.1.6  Provides tools to internationalize your application
symfony/twig-bundle                v6.1.1  v6.1.1  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v6.1.6  v6.1.6  Provides tools to validate values
symfony/web-link                   v6.1.0  v6.1.0  Manages links between resources
symfony/web-profiler-bundle        v6.1.6  v6.1.6  Provides a development tool that gives detailed information about the execution of any request
symfony/yaml                       v6.1.6  v6.1.6  Loads and dumps YAML files

Transitive dependencies not required in composer.json:
symfony/cache                      v6.1.5  v6.1.5  Provides extended PSR-6, PSR-16 (and tags) implementations
symfony/cache-contracts            v3.1.1  v3.1.1  Generic abstractions related to caching
symfony/config                     v6.1.3  v6.1.3  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/dependency-injection       v6.1.5  v6.1.5  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v3.1.1  v3.1.1  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v6.1.6  v6.1.6  Provides integration for Doctrine with various Symfony components
symfony/dom-crawler                v6.1.4  v6.1.4  Eases DOM navigation for HTML and XML documents
symfony/error-handler              v6.1.6  v6.1.6  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v6.1.0  v6.1.0  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v3.1.1  v3.1.1  Generic abstractions related to dispatching event
symfony/filesystem                 v6.1.5  v6.1.5  Provides basic utilities for the filesystem
symfony/finder                     v6.1.3  v6.1.3  Finds files and directories via an intuitive fluent interface
symfony/http-client-contracts      v3.1.1  v3.1.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v6.1.6  v6.1.6  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v6.1.6  v6.1.6  Provides a structured process for converting a Request into a Response
symfony/messenger                  v6.1.6  v6.1.6  Helps applications send and receive messages to/from other applications or via message queues
symfony/monolog-bridge             v6.1.2  v6.1.2  Provides integration for Monolog with various Symfony components
symfony/options-resolver           v6.1.0  v6.1.0  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v6.1.3  v6.1.3  Provides password hashing utilities
symfony/polyfill-intl-grapheme     v1.26.0 v1.26.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.26.0 v1.26.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.26.0 v1.26.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.26.0 v1.26.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.26.0 v1.26.0 Symfony polyfill for the Mbstring extension
symfony/routing                    v6.1.5  v6.1.5  Maps an HTTP request to a set of configuration variables
symfony/security-acl               v3.3.2  v3.3.2  Symfony Security Component - ACL (Access Control List)
symfony/security-core              v6.1.6  v6.1.6  Symfony Security Component - Core Library
symfony/security-csrf              v6.1.0  v6.1.0  Symfony Security Component - CSRF Library
symfony/security-http              v6.1.6  v6.1.6  Symfony Security Component - HTTP Integration
symfony/service-contracts          v3.1.1  v3.1.1  Generic abstractions related to writing services
symfony/translation-contracts      v3.1.1  v3.1.1  Generic abstractions related to translation
symfony/twig-bridge                v6.1.6  v6.1.6  Provides integration for Twig with various Symfony components
symfony/var-dumper                 v6.1.6  v6.1.6  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v6.1.3  v6.1.3  Allows exporting any serializable PHP data structure to plain PHP code
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 8.1.2 (cli) (built: Aug  8 2022 07:28:23) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies
    with Xdebug v3.1.2, Copyright (c) 2002-2021, by Derick Rethans
```

## Subject

When the SonataUser is stored in MongoDB, canonicalEmail and canonicalUsername are not updated at User creation. It is impossible to login in SonataAdmin using the created user.

This is due to vendor/sonata-project/user-bundle/src/Resources/config/listener.php contents: The Sonata\UserBundle\Listener\UserListener subscribe to `doctrine.event_subscriber` but not to `doctrine_mongodb.odm.event_subscriber`.

Adding theses lines to `services.yaml` fix the issue:

```yaml
    sonata.user.listener.user:
        class:   Sonata\UserBundle\Listener\UserListener
        arguments:
            - '@sonata.user.util.canonical_fields_updater'
            - '@sonata.user.manager.user'
        tags:
            -  { name: doctrine_mongodb.odm.event_subscriber, event: postPersist }
```

## Steps to reproduce

Setup SonataUserBundle with MongoDB following [SonataUserBundle documentation v6.x](https://docs.sonata-project.org/projects/SonataUserBundle/en/6.x/reference/installation/).

Use this User class to setup MongoDB successfully (SondataUserBundle does not define MongoDB attributes or annotations):

<details><summary>show</summary>
<p>

```php
<?php
// src/Document/SonataUserUser.php

namespace App\Document;

use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use Doctrine\Bundle\MongoDBBundle\Validator\Constraints as ODMConstraints;
use Sonata\UserBundle\Document\BaseUser;
use Symfony\Component\Validator\Constraints as Assert;

#[ODM\Document]
#[ODMConstraints\Unique(fields: "username")]
#[ODMConstraints\Unique(fields: "usernameCanonical")]
class SonataUserUser extends BaseUser
{
    #[ODM\Id()]
    protected $id;

    #[ODM\Field(type: "string")]
    #[ODM\Index()]
    #[Assert\NotBlank()]
    protected ?string $username = null;

    #[ODM\Field(type: "string")]
    #[ODM\Index()]
    protected ?string $usernameCanonical = null;

    #[ODM\Field(type: "string")]
    #[ODM\Index()]
    protected ?string $email = null;

    #[ODM\Field(type: "string")]
    #[ODM\Index()]
    protected ?string $emailCanonical = null;

    #[ODM\Field(type: "bool")]
    #[ODM\Index()]
    protected bool $enabled = false;

    #[ODM\Field(type: "string")]
    protected ?string $salt = null;

    #[ODM\Field(type: "string")]
    protected ?string $password = null;

    protected ?string $plainPassword = null;

    #[ODM\Field(type: "date")]
    protected ?\DateTimeInterface $lastLogin = null;

    #[ODM\Field(type: "string")]
    protected ?string $confirmationToken = null;

    #[ODM\Field(type: "date")]
    protected ?\DateTimeInterface $passwordRequestedAt = null;

    /**
     * The public representation of the user (e.g. a username, an email address, etc.)
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * Get the value of id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the value of id
     *
     * @return  self
     */
    public function setId($id): self
    {
        $this->id = $id;

        return $this;
    }
}
```

</p>
</details>

Create a user using:

```bash
symfony console sonata:user:create --super-admin username email@company.com password
```

## Expected results

the canonicalEmail and canonicalUsername fields are set in database, and it is ossible to login in SonataAdmin.

## Actual results

the canonicalEmail and canonicalUsername fields are not set in database, and it is impossible to login in SonataAdmin.

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

Closes #1578.

## Changelog

```markdown
### Fixed
- Ensure password is updated when it is the only field edited
- Register doctrine event subscribers both for ORM and ODM
```

### CODE REVIEW

File: src/Resources/config/orm.php [hunk 1]
```diff
@@ -32,5 +33,12 @@
                 new ReferenceConfigurator('doctrine'),
                 new ReferenceConfigurator('sonata.user.util.canonical_fields_updater'),
                 new ReferenceConfigurator($passwordHasherId),
+            ])
+
+        ->set('sonata.user.listener.user', UserListener::class)
+            ->tag('doctrine.event_subscriber')
```
Comment (jordisala1991) [inline src/Resources/config/orm.php]:
```suggestion
           // ->tag('doctrine.event_subscriber')
```

File: src/Resources/config/orm.php [hunk 2]
```diff
@@ -32,5 +33,12 @@
                 new ReferenceConfigurator('doctrine'),
                 new ReferenceConfigurator('sonata.user.util.canonical_fields_updater'),
                 new ReferenceConfigurator($passwordHasherId),
+            ])
+
+        ->set('sonata.user.listener.user', UserListener::class)
+           // ->tag('doctrine.event_subscriber')
```
Comment (jordisala1991) [inline src/Resources/config/orm.php]:
```suggestion
           ->tag('doctrine.event_subscriber')
```

File: tests/Functional/Admin/UserAdminTest.php [hunk 3]
```diff
@@ -107,6 +107,7 @@ public function testUpdatePassword(): void
             'uniqid' => 'user',
         ]);
         $client->submitForm('btn_update_and_list', [
+            'user[enabled]' => false,
```
Comment (jordisala1991) [inline tests/Functional/Admin/UserAdminTest.php]:
```suggestion

```

File: src/Model/User.php [hunk 4]
```diff
@@ -260,6 +260,7 @@ public function setSuperAdmin(bool $boolean): void
     public function setPlainPassword(?string $password): void
     {
         $this->plainPassword = $password;
+        $this->updatedAt = new \DateTime();
```
Comment (jordisala1991) [inline src/Model/User.php:267]:
```suggestion
        // Do not remove this, it will trigger preUpdate doctrine event
        // when you only change the password, since plainPassword 
        // is not persisted on the entity, doctrine does not watch for it.
        $this->updatedAt = new \DateTime();
```

File: src/Model/User.php [hunk 5]
```diff
@@ -260,6 +260,10 @@ public function setSuperAdmin(bool $boolean): void
     public function setPlainPassword(?string $password): void
     {
         $this->plainPassword = $password;
+        // Do not remove this, it will trigger preUpdate doctrine event
```
Comment (jordisala1991) [inline src/Model/User.php:264]:
```suggestion

        // Do not remove this, it will trigger preUpdate doctrine event
```

File: src/Admin/Model/UserAdmin.php [hunk 6]
```diff
@@ -31,16 +31,14 @@ class UserAdmin extends AbstractAdmin
 {
     protected $classnameLabel = 'user';
 
+    /**
+     * NEXT_MAJOR: Remove $userManager dependency and construct
```
Comment (jordisala1991) [inline src/Admin/Model/UserAdmin.php]:
```suggestion
     * NEXT_MAJOR: Remove $userManager dependency and construct.
```

File: src/Model/User.php [hunk 7]
```diff
@@ -260,6 +260,10 @@ public function setSuperAdmin(bool $boolean): void
...
+        // when you only change the password, since plainPassword
```
Comment (jordisala1991) [inline src/Model/User.php]:
```suggestion
        // when you only change the password, since plainPassword
```

**Comment by jordisala1991** [comment]
There are 2 fixes here: To be squashed.

1. Events for odm and orm are different. lets declare those on the specific files for it.
2. When you only update password, preUpdate was not triggered, since it is a field not managed by doctrine. Updating updatedAt property, fixes the problem.

The second point makes the UserAdmin preUpdate hook not necessary. The function can be removed but not the dependency, since it is protected and not final. I have just added a NEXT_MAJOR comment.

We could definitely use tests for odm integration, but not sure how to do it, tbh, need to think about it.

**Review by VincentLanglet — APPROVED** [review]
